using AIIsland.Core;
using AIIsland.Services;
var tests = 0;
void Check(bool condition, string name) { if (!condition) throw new Exception(name); tests++; Console.WriteLine("PASS " + name); }
var state = new IslandState();
var at = DateTimeOffset.UtcNow;
IslandEvent E(string kind, int seconds, string session = "a", string provider = "Codex") => new(provider, session, kind, at.AddSeconds(seconds));
state.Apply(E("SessionStart", 0));
Check(state.Visible(at).Length == 0, "CLI online is not thinking");
state.Apply(E("UserPromptSubmit", 1));
Check(state.Sessions.Single().Status == AIStatus.Thinking, "Prompt starts a task");
state.Apply(E("PreToolUse", 2)); state.Apply(E("PostToolUseFailure", 3));
Check(state.Sessions.Single().Status == AIStatus.Thinking, "Tool failure does not fail task");
state.Apply(E("PermissionRequest", 4));
Check(state.Sessions.Single().Status == AIStatus.WaitingForApproval, "Approval is distinct");
state.Apply(E("Stop", 5));
Check(state.Sessions.Single().Elapsed(at.AddSeconds(20)) == TimeSpan.FromSeconds(4), "Completion freezes task elapsed");
Check(state.Visible(at.AddSeconds(7)).Length == 1 && state.Visible(at.AddSeconds(8)).Length == 0, "Completion expires after three seconds");
Check(!state.Apply(E("PreToolUse", 2)), "Late events ignored");
Check(!state.Apply(E("Stop", 5)), "Duplicate events ignored");
state.Apply(E("UserPromptSubmit", 6));
Check(state.Visible(at.AddSeconds(9)).Single().Active, "New task survives previous completion deadline");
state.Apply(E("UserPromptSubmit", 7, "b")); state.Apply(E("UserPromptSubmit", 7, "a", "Claude"));
Check(state.Visible(at.AddSeconds(9)).Length == 3, "Same-provider and cross-provider sessions independent");
state.Apply(E("SessionEnd", 10));
Check(state.Sessions.First().Status == AIStatus.Ended, "Session exit does not imply success");
Check(!state.Apply(E("Bogus", 11)), "Unknown event rejected");
state.Clear(); Check(!state.Sessions.Any(), "Pause reset clears task state");
state.Apply(E("UserPromptSubmit", 20) with { TurnId = "new" });
Check(!state.Apply(E("Stop", 21) with { TurnId = "old" }) && state.Sessions.Single().Active, "Previous turn completion cannot stop new task");
Check(!state.Apply(E("StopFailure", 21) with { TurnId = "old" }) && state.Sessions.Single().Active, "Previous turn failure cannot stop new task");
state.Apply(E("PreToolUse", 22) with { TurnId = "new", ToolId = "tool-a" });
state.Apply(E("PreToolUse", 23) with { TurnId = "new", ToolId = "tool-b" });
state.Apply(E("PostToolUse", 24) with { TurnId = "new", ToolId = "tool-a" });
Check(state.Sessions.Single().Status == AIStatus.Executing, "Parallel tool completion keeps remaining tool active");
state.Apply(E("PostToolUse", 25) with { TurnId = "new", ToolId = "tool-b" });
Check(state.Sessions.Single().Status == AIStatus.Thinking, "Last tool returns to thinking");
state.Apply(E("UserPromptSubmit", 26, "c", "Claude"));
state.RemoveProvider("Codex");
Check(state.Sessions.Single().Provider == "Claude" && state.Sessions.Single().Active, "Provider toggle preserves other active tasks");
var terminal = new IslandState();
terminal.Apply(E("UserPromptSubmit", 1) with { TurnId = "turn-a" });
terminal.Apply(E("PreToolUse", 2) with { TurnId = "turn-a", ToolId = "tool-a" });
terminal.Apply(E("PreToolUse", 3) with { TurnId = "turn-a", ToolId = "tool-b" });
Check(terminal.Apply(E("Stop", 4)) && terminal.Sessions.Single().Status == AIStatus.Completed
    && terminal.Sessions.Single().ActiveTools.Count == 0 && terminal.Sessions.Single().EndedAt == at.AddSeconds(4),
    "Completion without turn ID ends the current task and clears active tools");
terminal.Apply(E("UserPromptSubmit", 5) with { TurnId = "turn-b" });
terminal.Apply(E("PreToolUse", 6) with { TurnId = "turn-b", ToolId = "tool-c" });
terminal.Apply(E("PreToolUse", 7) with { TurnId = "turn-b", ToolId = "tool-d" });
Check(terminal.Apply(E("SessionEnd", 8)) && terminal.Sessions.Single().Status == AIStatus.Ended
    && terminal.Sessions.Single().Connection == ConnectionStatus.Offline && terminal.Sessions.Single().ActiveTools.Count == 0,
    "Session exit without turn ID ends all active tools");
var projects = new IslandState();
projects.Apply(E("SessionStart", 1, "project-a") with { WorkingDirectory = @"D:\go_space\src\AI-Island" });
projects.Apply(E("UserPromptSubmit", 2, "project-a") with { WorkingDirectory = @"D:\elsewhere" });
Check(projects.Sessions.Single().ProjectName == "AI-Island", "Startup project survives later cwd changes");
projects.Apply(E("SessionStart", 3, "project-b") with { WorkingDirectory = @"E:\other\AI-Island" });
Check(ProjectNames.Display(projects.Sessions.First(), projects.Sessions).Contains(@"D:\go_space\src"), "Same-name projects include parent directory");
projects.Apply(E("SessionStart", 4, "project-c") with { WorkingDirectory = @"D:\go_space\src\AI-Island" });
Check(ProjectNames.Display(projects.Sessions.First(), projects.Sessions).Contains("project-"), "Same-directory sessions get session suffix");
Check(ProjectNames.Display(projects.Sessions.First(), projects.Sessions) != ProjectNames.Display(projects.Sessions.Last(), projects.Sessions), "Colliding short session prefixes stay distinguishable");
Check(ProjectNames.Name(ProjectNames.Normalize(@"D:\项目\灵动岛\")) == "灵动岛", "Unicode and trailing separator supported");
Check(ProjectNames.Normalize("relative/path") == null && ProjectNames.Name(null) == "未知项目", "Missing or relative cwd does not guess project");
projects.Apply(E("Stop", 5, "project-a")); projects.Expire(at.AddHours(2));
Check(projects.Sessions.Count() == 3, "Online sessions are not expired after one hour");
projects.Apply(E("SessionEnd", 6, "project-b"));
Check(projects.Sessions.Single(x => x.SessionId == "project-b").Connection == ConnectionStatus.Offline, "Idle session exit marks offline");
Check(!projects.Apply(E("PostToolUse", 7, "project-b")) && projects.Sessions.Single(x => x.SessionId == "project-b").Connection == ConnectionStatus.Offline, "Late tool events do not revive closed sessions");
var legacy = System.Text.Json.JsonSerializer.Deserialize<IslandEvent>("{\"Provider\":\"Codex\",\"SessionId\":\"old\",\"Kind\":\"SessionStart\",\"At\":\"2026-09-15T00:00:00Z\"}");
Check(legacy?.WorkingDirectory == null, "Legacy event schema remains compatible");
var proxy = new ProxySnapshot(3, "127.0.0.1:7897", "<local>", "");
Check(ProxyPolicy.Conflict(proxy, "127.0.0.1:7897", false) == null, "Owned system proxy can be toggled");
Check(ProxyPolicy.Conflict(proxy with { Server = "127.0.0.1:8888" }, "127.0.0.1:7897", false) != null, "Foreign proxy is protected");
Check(ProxyPolicy.Conflict(proxy with { Flags = 5 }, "127.0.0.1:7897", false) != null, "PAC conflict blocks mutation");
Check(ProxyPolicy.Conflict(proxy, "127.0.0.1:7897", true) != null, "Proxy guard blocks mutation");
Check(!ProxyPolicy.Matches("http=127.0.0.1:7897;https=127.0.0.1:8888", "127.0.0.1:7897"), "Mixed proxy endpoints are not mistaken for Clash");
CodexCompletionChecks.Run(Check);
Console.WriteLine($"{tests} tests passed");
